### PR TITLE
Update cedar core to the last version

### PR DESCRIPTION
**Pull request by cleissonbarbosa**

### CODE REVIEW

**Comment by omer9564** [comment]
Sorry for the delay, will address this next week

**Review by omer9564 — CHANGES_REQUESTED** [review]
@cleissonbarbosa Looks good in general but it looks like the tests are failing:
```
warning: unused import: `exit`
 --> src/main.rs:5:20
  |
5 | use std::process::{exit, ExitCode};
  |                    ^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: `cedar-agent` (bin "cedar-agent" test) generated 1 warning (1 duplicate)
warning: `cedar-agent` (bin "cedar-agent") generated 1 warning (run `cargo fix --bin "cedar-agent"` to apply 1 suggestion)
    Finished test [unoptimized + debuginfo] target(s) in 36.94s
     Running unittests src/lib.rs (target/debug/deps/cedar_agent-cc305950ed40fc42)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/main.rs (target/debug/deps/cedar_agent-33ce84b307e1916e)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/mod.rs (target/debug/deps/mod-9636ee89653b5494)

running 4 tests
test services::data_tests::test_load_entities_from_file ... ok
test services::policies_tests::test_load_policies_from_file ... ok
test services::policies_tests::memory_tests ... ok
test services::data_tests::memory_tests ... FAILED

failures:

---- services::data_tests::memory_tests stdout ----
thread 'services::data_tests::memory_tests' panicked at 'called `Result::unwrap()` on an `Err` value: DeserializationError(ActionParentIsNonAction { uid: EntityUID { ty: Concrete(Name { id: Id("Action"), path: [] }), eid: Eid("document:delete") }, parent: EntityUID { ty: Concrete(Name { id: Id("ResourceType"), path: [] }), eid: Eid("document") } })', tests/services/data_tests.rs:15:75
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    services::data_tests::memory_tests

test result: FAILED. 3 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.03s

error: test failed, to rerun pass `--test mod`
```

**Comment by cleissonbarbosa** [comment]
@omer9564 Tks for the review, as of version `2.3.1`, cedar only accepts parents of the same type in Actions, that is, [the parents of actions must be actions](https://docs.rs/cedar-policy-core/2.3.2/cedar_policy_core/entities/enum.JsonDeserializationError.html#variant.ActionParentIsNonAction), this may be a break change for some users

**Comment by omer9564** [comment]
we don't mind introducing a major change if that is the case.
@cleissonbarbosa I still get failure when running `cargo test` . 
Screen Shot 2023-11-13 at 10 17 54

**Comment by cleissonbarbosa** [comment]
@omer9564 adjusted.

**Review by omer9564 — APPROVED** [review]
Approved 🥳

**Comment by omer9564** [comment]
@cleissonbarbosa I will release a new `cedar-agent` version later on this week or early next week 🙂

**Pull request merged**
